title: monthly5Rock blog
markdown: kramdown
theme: ["hugo-video", "my-theme"]

# for atom feed
author:
  name: Eugene Kang
  email: monthly5Rock@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-spaceship

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
